# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

before_script:
  - echo `pwd`
  - sudo apt-get update -qq && sudo apt-get install -y -qq python-pip mercurial
  - which npm || (curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash ; sudo apt-get install -y nodejs)
  - sudo pip install -r build_requirements.txt
  - python ensure_dependencies.py

stages:
  - test
  - build
  - deploy

npmtests:
  stage: test
  script: ./runtests

build-nightly:
  stage: build
  script:
    - whoami
    - python build.py build -t gecko
      #  only:
      #    - ci

build-release:
  stage: deploy
  script:
    - whoami
  only:
    - tags

deploy-nightly:
    stage: deploy
    script: echo $AMO_KEY
